### ISSUE TITLE
Rendering breaks with devtools

### ISSUE THREAD

**Issue by benjamin-thomas** [casid/jte-spring-boot-demo#1]
Hello,

The current demo is unfortunately incompatible with spring's devtools.

Add the following dependency:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-devtools</artifactId>
	<scope>runtime</scope>
	<optional>true</optional>
</dependency>
```

And JTE will complain about a weird type mismatch error.

    Failed to render demo.jte, type mismatch for parameter:
        Expected gg.jte.demo.DemoModel, got gg.jte.demo.DemoModel

Luckily, I already hit that problem here: https://github.com/casid/jte/issues/73

So my quick and dirty solution was to grab [this suboptimal file](https://github.com/benjamin-thomas/javalite-jte-demo/blob/8668912b8762976b7291165f2c022cc52935a1db/src/main/java/app/utils/JTE.java), then do this:

```java
@GetMapping("/jte")
@ResponseBody
public String viewJTE() {
    visitsRepository.add();

    DemoModel model = new DemoModel();
    model.name = "unknown visitor";
    model.visits = visitsRepository.get();

    return JTE.render("demo.jte", model, getClass().getClassLoader());
}
```

Could your recommend a better approach? I suppose you'd prefer to provide an example with proper devtools integration?

The devtools module is nice since you can change the model's data, press F9 with IntelliJ, then you browser auto refreshes (if using [that plugin](https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei))

Thanks ;)

**Comment by casid** [comment]
Hey @benjamin-thomas, thanks for reporting and for the late reply!

I could reproduce your finding and pushed a fix to the demo repository. Let me know if this works for you as well.

**Comment by benjamin-thomas** [comment]
No worries, I hope you enjoyed your week-end ;)

So damn that was a simple fix, I keep forgetting java has method overloading :p

Please see my PR as the template was rendering fine, but the auto-reload mechanism wouldn't trigger otherwise.

I'm really happy you've put this out there. I've been looking at how to bring as much type safety as possible in a practical way to evolve a complicated web project I'm struggling with, and I think I finally found a great combo with JTE + Spring Data JPA!!

Great job, I love what you've done here, JTE is a pleasure to use!

**Comment by casid** [comment]
Thanks so much for the kind words! I'm glad you're enjoying jte!
