### ISSUE TITLE
Please clarify the production workflow

### ISSUE THREAD

**Issue by benjamin-thomas** [casid/jte-spring-boot-demo#3]
Hello @casid,

I'm trying to deploy a demo to a heroku instance, could you give me a nudge and have a look [at this branch](https://github.com/benjamin-thomas/jte-spring-boot-demo/commits/heroku-deploy)? (I'd like to document the params required for such a setup).

This is roughly the error I get (whether I'm deploying to heroku or running the jar on my local dev machine):

---

    2021-05-25 15:07:36.339  INFO 9579 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
    2021-05-25 15:07:37.063 ERROR 9579 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is gg.jte.TemplateException: Failed to compile template, error at demo.jte:1
    /home/benjamin/IdeaProjects/jte-spring-boot-demo/jte-classes/gg/jte/generated/ondemand/JtedemoGenerated.java:2: error: package gg.jte.demo does not exist
    import gg.jte.demo.DemoModel;
                      ^
    /home/benjamin/IdeaProjects/jte-spring-boot-demo/jte-classes/gg/jte/generated/ondemand/JtedemoGenerated.java:6: error: package gg.jte.runtime does not exist
     private static final gg.jte.runtime.BinaryContent BINARY_CONTENT = gg.jte.runtime.BinaryContent.load(JtedemoGenerated.class, "JtedemoGenerated.bin", 7,35,1);

---

Obviously I'm missing a dependency somehow.

---

This is the command I run on my dev host:

    ./mvnw -DskipTests clean dependency:list install # this is what heroku generates on deploy
    java -jar ./target/demo-0.0.1-SNAPSHOT.jar # I suppose this is what heroku runs, not sure 
    java -jar ./target/demo-0.0.1-SNAPSHOT.jar -cp jte-classes/ # me trying to resolve the dependency by hand, I'm not going anywhere with this ;)

---

I'm a little confused about the workflow here, could you give me a hint? (please note I'm not a java dev)

The rest of the stack runs fine so I gather the setup is wrong here.

**Comment by casid** [comment]
Hey, this looks like a class loader problem. The class loader that the TemplateEngine uses seems to have no access to the classes of your application. Hence, `gg.jte.demo.DemoModel` cannot be found.

I looked at your branch and you're using the generate task to create the jte classes. This means those classes will generated by the maven plugin and bundled together with your application. To use those, the `TemplateEngine` needs to be created a bit differently.

Is the Heroku app working, if you integrated this commit (https://github.com/casid/jte-spring-boot-demo/commit/d5ce80a4e0c7a962239badbfafef8ba81aa400f8) into your branch and run a mvn install?

Also, do you know if there's a way to tell if a spring boot application is running in dev mode or in production mode? I left a pretty ugly todo in this commit :-D
https://github.com/casid/jte-spring-boot-demo/blob/d5ce80a4e0c7a962239badbfafef8ba81aa400f8/src/main/java/gg/jte/demo/TemplateRenderer.java#L19

**Comment by benjamin-thomas** [comment]
Thanks! I'll look into it soon (this weekend or next week)

I used the generate task because I gathered I was missing a dependency and that would solve it.

Regarding differentiating dev/prod, unless I'm mistaken one has to create the concept of a "profile", and that's driven via annotations.

I'm a spring noob though, so I'll report back my findings and propose updating the setup if you're ok with that.

**Comment by casid** [comment]
I'm closing this, I think it works pretty well now after your changes, right? Feel free to reopen if I'm wrong :-)

**Comment by benjamin-thomas** [comment]
> I'm closing this, I think it works pretty well now after your changes, right? Feel free to reopen if I'm wrong :-)

Thanks. I did intend to get back into exploring JTE soon. I wanted to cleanup some stuff put didn't have the time. I'll report my findings if necessary via other PRs.

Do you think it'd be okay to upgrade the demo and include full app features (db, login, etc.)?

Although not strictly related to JTE per se, I think it'd be useful to see JTE in action within a full app context.

As I mentioned in our earlier conversations, I'm interested in introducing as much type safety as possible so I would propose changes along this line.

**Comment by casid** [comment]
That's cool! Sure, a fully working sample application would be nice. Maybe have it as a separate repository?

**Comment by benjamin-thomas** [comment]
> That's cool! Sure, a fully working sample application would be nice. Maybe have it as a separate repository?

Sounds good to me ;)

What do you have in mind? A repo under "casid/jte-spring-boot-demo-fullstack" or something like that?

I could put the repo under my name, but that wouldn't be ideal since I'd also be interested to get feedback from other JTE users.

**Comment by casid** [comment]
I think you can definitely put it under your name. I mean, you'd be the main contributor on that project! And casid isn't very jte specific either :-D

Let me know when you think it is ready to be shown and I will definitely put a link to it on the jte readme!

**Comment by benjamin-thomas** [comment]
> And casid isn't very jte specific either :-D

Sure ;)

My reasoning was that I tend to look around a maintainer's repos once I find an interesting project so I was thinking of discoverability.

Ok I'll keep you posted here once I have something to show.
