### ISSUE TITLE
use ViewResolver

### ISSUE THREAD

**Issue by Alwan** [casid/jte-spring-boot-demo#5]
For better integration with spring framework use ViewResolver to render.
below example 
https://github.com/Alwan/sjws
the configuration need some improvement. Not working in prod profile

**Comment by casid** [comment]
Sure, but it loses the type safety jte provides:

```
<h1>${model.get("greetings")}</h1>
```

Did you run the precompiler through `mvn package` to precompile templates before you started the prod profile?

**Comment by Alwan** [comment]
I updated the example 
you can do some casting. 

```
@import app.sjws.IndexPage
@param java.util.Map<String, Object> model
!{IndexPage page =  (IndexPage) model.get("page");}
```

**Comment by casid** [comment]
Still quite ugly compared to the plain jte example, isn't it?

```
@import gg.jte.demo.DemoModel

@param DemoModel model

Hello ${model.name}!
<br>
<br>
You are visitor number ${model.visits}.
```

**Comment by Alwan** [comment]
I updated the config I am able to make it work without casting just like the example you used.
more testing is needed for some spring mvc features
